include(CMakeFindDependencyMacro)
find_package(Eigen3 3.3.7 CONFIG REQUIRED)
if(NOT ${jsoncpp_FOUND})
	find_package(jsoncpp 1.9 CONFIG REQUIRED)
endif()
find_package(CUDA REQUIRED)
include("${CMAKE_CURRENT_LIST_DIR}/cupoch_cameraTargets.cmake")