include(CMakeFindDependencyMacro)
find_package(Eigen3 3.3.7 CONFIG REQUIRED)
find_package(JPEG REQUIRED)
if(NOT ${jsoncpp_FOUND})
	find_package(jsoncpp CONFIG REQUIRED)
endif()
find_package(tinyobjloader CONFIG REQUIRED)
find_package(rply CONFIG REQUIRED)
find_package(libpng CONFIG REQUIRED)
find_package(CUDA REQUIRED)
include("${CMAKE_CURRENT_LIST_DIR}/cupoch_ioTargets.cmake")