include(CMakeFindDependencyMacro)
find_package(cupoch_utility CONFIG REQUIRED)
find_package(cupoch_camera CONFIG REQUIRED)
find_package(cupoch_geometry CONFIG REQUIRED)
find_package(cupoch_collision CONFIG REQUIRED)
find_package(cupoch_integration CONFIG REQUIRED)
find_package(cupoch_registration CONFIG REQUIRED)
find_package(cupoch_odometry CONFIG REQUIRED)
find_package(cupoch_planning CONFIG REQUIRED)
find_package(cupoch_io CONFIG REQUIRED)
include("${CMAKE_CURRENT_LIST_DIR}/cupochTargets.cmake")